fix error

diff --git a/.github/workflows/06-deploy-to-aks-k8s.yml b/.github/workflows/06-deploy-to-aks-k8s.yml
--- a/.github/workflows/06-deploy-to-aks-k8s.yml
+++ b/.github/workflows/06-deploy-to-aks-k8s.yml
@@ -34,14 +34,16 @@ jobs:
           kubectl get nodes
       - name: Deploy to Kubernetes
         run: |
+          set -e   # stop script if any command fails
+
           kubectl set image deployment/nginx-deploy nginx=httpd:latest
           echo "Deployment initiated"
-          set +e
-          kubectl rollout status deployment/nginx-deploy --timeout=60s
-          if [ $? -ne 0 ]; then
+
+          # Wait for rollout
+          if ! kubectl rollout status deployment/nginx-deploy --timeout=60s; then
             echo "Rollout failed, initiating rollback"
             kubectl rollout undo deployment/nginx-deploy
             exit 1
           else
-            echo "Rollout successful"  
-          fi  
+            echo "Rollout successful"
+          fi 
